name: Ndasmu_ErDePe

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://gitlab.com/samb1/fix_why/-/raw/main/cok/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://gitlab.com/samb1/fix_why/-/raw/main/cok/nssm.exe -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://gitlab.com/samb1/fix_why/-/raw/main/cok/ngrok-us.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://gitlab.com/samb1/fix_why/-/raw/main/cok/cek.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://gitlab.com/samb1/fix_why/-/raw/main/cok/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://gitlab.com/samb1/fix_why/-/raw/main/cok/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://gitlab.com/samb1/fix_why/-/raw/main/cok/loop.bat -OutFile loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-US.bat

    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.jpg D:\a\wallpaper.jpg
        copy wallpaper.bat D:\a\wallpaper.bat
        
    - name: Create Tunnel
      run: sc start ngrok
      
    - name: Programmed and developed by "Ndasmu"
      run: echo https://t.me/wahyubwi1609
      
    - name: All Done! 
      run: cmd /c NGROK-CHECK.bat
      
    - name: Enjoy.
      run: cmd /c loop.bat
